# Generated by Django 5.2.17 on 2026-09-16 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicactivity',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='googlecalendarcredential',
            options={'ordering': ['google_email']},
        ),
        migrations.RemoveConstraint(
            model_name='academicactivity',
            name='unique_event_per_user',
        ),
        migrations.AddField(
            model_name='academicactivity',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='activities.googlecalendarcredential'),
        ),
        migrations.AddField(
            model_name='googlecalendarcredential',
            name='google_email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='googlecalendarcredential',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='academicactivity',
            constraint=models.UniqueConstraint(fields=('credential', 'google_event_id'), name='unique_event_per_credential'),
        ),
        migrations.AddConstraint(
            model_name='googlecalendarcredential',
            constraint=models.UniqueConstraint(fields=('user', 'google_email'), name='unique_google_account_per_user'),
        ),
    ]
